services:

  transaction-service:
    image: openjdk:22-jdk-oracle
    container_name: transactionimage
    ports:
      - "${SERVICE_PORT1}:8080"
      - "${SERVICE_PORT2}:8000"
    env_file:
        - .env
    depends_on:
      - transaction-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/TransactionService-v1.0.8.jar:/app/app.jar

    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  transaction-db:
    image: mongo:latest
    container_name: transactiondb
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongo_transaction:/etc/mongo
      - mongo_transaction_data:/data/db
      - mongo_transaction_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:

volumes:
  mongo_transaction:
  mongo_transaction_data:
  mongo_transaction_config: