services:

  payment-service:
    image: openjdk:22-jdk-oracle
    container_name: paymentimage
    ports:
      - 8082:8080
      - 8002:8000
    depends_on:
      - payment-db
    networks:
      - greenspot-net
    volumes:
      - ./build/libs/PaymentService-v0.0.2.jar:/app/app.jar
    working_dir: /app
    entrypoint: java -Xdebug -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar /app/app.jar

  payment-db:
    image: mongo:latest
    container_name: paymentdb
    ports:
      - 27017
    volumes:
      - mongo_payment:/etc/mongo
      - mongo_payment_data:/data/db
      - mongo_payment_config:/data/configdb
    networks:
      - greenspot-net

networks:
  greenspot-net:
    name: greenspot_net

volumes:
  mongo_payment:
  mongo_payment_data:
  mongo_payment_config: